[cursor]
blink_interval = 250
blink_timeout = 0

[cursor.style]
blinking = "Always"
shape = "Beam"

[font]
size = 14.0

[font.bold]
family = "HackGen Console NF"
style = "Bold"

[font.bold_italic]
family = "HackGen Console NF"
style = "Bold Italic"

[font.italic]
family = "HackGen Console NF"
style = "Italic"

[font.normal]
family = "HackGen Console NF"
style = "Regular"

[scrolling]
history = 100000
multiplier = 3

[selection]
save_to_clipboard = true

[window]
opacity = 0.9
blur = true
startup_mode = "Maximized"
padding = { x = 4, y = 4 }

[general]
live_config_reload = true
import = ["/Users/itxryx/.config/alacritty/dracula.toml"]

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux a -t 0 || tmux"] }

[env]
TERM = "alacritty"

